Team 1 1.1.2
podolyanyn/py104_phone_book_project pull request #7
Opened 2023-06-20 08:20 UTC by Nikatin3000

Team 1 1.1.2 - add Contact methods

2023-06-20 10:40 UTC, AnatoliiDomanskii requested changes

2023-06-20 10:40 UTC, AnatoliiDomanskii commented on app/contact.py
> +    all_contacts = []
Цей список весь час пустий.
необхідно реалізувати додавання об'єтку класу в цей список при створені.
для цього достатньо додати в __ init __ ->
all_contacts.append(self)
або 
Contact.all_contacts.append(self)

2023-06-20 10:52 UTC, Nikatin3000 commented on app/contact.py
> +    all_contacts = []
так ?

2023-06-20 10:53 UTC, AnatoliiDomanskii approved these changes

2023-06-22 07:32 UTC, AnatoliiDomanskii approved these changes

2023-06-22 07:32 UTC, merged